version: '3'

services:
  app:
    image: pratik180797/bsc23grassroots:tagname
    container_name: bsc23grassroots
    restart: always
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production