name: Build on DockerHub and Deploy to AWS
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: /Source/Dockerfile
          tags: pratik180797/bsc23grassroots:tagname
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-234-62-236.compute-1.amazonaws.com 'sudo docker pull pratik180797/bsc23grassroots:tagname'
    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-234-62-236.compute-1.amazonaws.com 'sudo docker stop bsc23grassroots || true'
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-234-62-236.compute-1.amazonaws.com 'sudo docker rm bsc23grassroots || true'
    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-234-62-236.compute-1.amazonaws.com 'sudo docker run -d --name bsc23grassroots -p 8000:8000 pratik180797/bsc23grassroots:tagname'
